# Generated by Django 2.2.11 on 2020-07-09 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20200709_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='email',
        ),
    ]
